name: voucher_manager
description: An app to save, search, categorize, and receive expiry alerts for vouchers from different sources

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# Version 1+1 means version 1.0.0 with build number 1.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  lottie: ^2.6.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.0.5
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  
  # Image Processing
  image_picker: ^1.0.4
  google_ml_kit: ^0.16.3
  path_provider: ^2.1.1
  
  # Notifications
  flutter_local_notifications: ^15.1.0+1
  
  # Utils
  intl: ^0.18.1
  permission_handler: ^10.4.3
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  sqflite_common_ffi: ^2.3.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
